# Azure DevOps YAML Pipeline from Bow Data Toolkits

trigger:
    branches:
        include:
            - "*"


resources:
    repositories:
        - repository: bowdata-toolkits
          type: git
          name: toolkits/bowdata.toolkits.azure-pipelines
          ref: refs/heads/master
        - repository: bowdata-go-pipelines
          type: git
          name: toolkits/bowdata.toolkits.go-pipeline-templates
          ref: refs/heads/master



parameters:
# general params
  - name: logLevel
    default: debug
    type: string
    displayName: "Log Level"
    values:
      - panic
      - fatal
      - error
      - warn
      - info
      - debug
      - trace
  - name: buildStageName
    default: Build
  - name: WorkingDirectory
    default: $(Build.SourcesDirectory)
  - name: goModuleName
    default: bowdata.test.go_module_template
## Version Stage Parameter Set
  - name: _version_stage_params
    type: object
    default:
      - versionStageName
      - versionStageDisplayName
      - versionStageDependsOn
      - versionStageCondition
      - versionStageVariables
      - preRelease
      - useForceVersion
  - name: versionStageName
    default: Version
  - name: versionStageDisplayName
    default: 'Version Stage'
  - name: versionStageDependsOn
    type: object
    default: ['Build']
  - name: versionStageCondition
    default: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  - name: versionStageVariables
    type: object
    default: {}
  - name: preRelease
    default: "a"
  - name: useForceVersion
    type: boolean
    default: false



stages:
  - template: /pipelines/module-pipeline.yaml@bowdata-go-pipelines
    parameters:
      logLevel: ${{parameters.logLevel}}
      buildStageName: ${{parameters.buildStageName}}
      workingDirectory: ${{parameters.WorkingDirectory}}

  - template: /containers/stages/azure-docker-stage.yaml@bowdata-toolkits
    parameters:
      ${{ each pair in parameters }}:
        ${{if and(or(containsValue(parameters._azure_docker_stage_params, pair.key), containsValue(parameters._general_params, pair.key)), not(containsValue(parameters._ignore_params, pair.key)))}}:
          ${{pair.key}}: ${{pair.value}}
      dockerRunPostSteps:

        - script: |
            status_code=$(curl --write-out %{http_code} --silent --output /dev/null http://localhost:${{parameters.hostPort}}/)
            if [[ "$status_code" -ne 200 ]] ; then
              echo "Received status $status_code" Expected 200; exit 1
            else
              exit 0
            fi
          displayName: "Smoke Test: WebApp"
          name: SmokeTest_App
          workingDirectory: ${{parameters.workingDirectory}}

  - template: /python/stages/version-stage.yaml@bowdata-toolkits
    parameters:
      ${{ each pair in parameters }}:
        ${{if and(or(containsValue(parameters._version_stage_params, pair.key), containsValue(parameters._general_params, pair.key)), not(containsValue(parameters._ignore_params, pair.key)))}}:
          ${{pair.key}}: ${{pair.value}}
